[nfs]
172.31.91.193 ansible_ssh_user='ec2-user'

[webservers]
172.31.85.180 ansible_ssh_user='ec2-user'
172.31.81.54  ansible_ssh_user='ec2-user'
172.31.85.66  ansible_ssh_user='ec2-user'

[db]
172.31.82.208 ansible_ssh_user='ec2-user'

[lb]
172.31.80.228 ansible_ssh_user='ubuntu'

[uat-webservers]
172.31.92.191 ansible_ssh_user='ec2-user'
172.31.86.205 ansible_ssh_user='ec2-user'
